from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(simulation_results, filepath="strategy_report.pdf"):
    """
    Generates a PDF report based on simulation results.
    simulation_results: list of dicts (one per segment simulation)
    """
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph("AI Pricing Strategy Report", title_style))
    story.append(Spacer(1, 12))

    # Executive Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    summary_text = ("This report analyzes the potential impact of pricing adjustments across your customer segments. "
                    "Our AI models have simulated demand elasticity and churn risk to provide these recommendations.")
    story.append(Paragraph(summary_text, styles['Normal']))
    story.append(Spacer(1, 12))

    # Detailed Simulation Results
    story.append(Paragraph("Simulation Results & Recommendations", styles['Heading2']))
    
    for res in simulation_results:
        segment = res['segment']
        story.append(Paragraph(f"Segment: {segment}", styles['Heading3']))
        
        # Recommendation Logic (Simplified)
        recomm = "HOLD"
        simple_explanation = "Keeping the price the same is safe, but we might be leaving money on the table."
        
        if res['revenue_uplift_pct'] > 5 and res['churn_probability'] < 0.2:
            recomm = "IMPLEMENT INCREASE"
            simple_explanation = "A price increase here is a great idea! Most customers will stay, and you will make significantly more money."
        elif res['revenue_uplift_pct'] < 0:
            recomm = "AVOID - REVENUE LOSS"
            simple_explanation = "Do not do this. You will lose money because too many people will quit or the price is too low."
        elif res['churn_probability'] > 0.3:
            recomm = "CAUTION - HIGH CHURN RISK"
            simple_explanation = "This is risky. You will make more money per person, but a lot of people will cancel."

        data = [
            ["Metric", "Value"],
            ["Proposed Price", f"${res['new_price']:.2f}"],
            ["Revenue Impact", f"{res['revenue_uplift_pct']:.2f}%"],
            ["Churn Probability", f"{res['churn_probability']:.2%}"],
            ["Est. Cust. Lifetime Value (CLTV)", f"${res.get('cltv', 0):,.2f}"],
            ["Risk Level", f"{res['risk_label']} ({res['risk_score']})"],
            ["Recommendation", recomm]
        ]
        
        t = Table(data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (1, 0), colors.Color(0.1, 0.2, 0.4)), # Dark Blue
            ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.Color(0.95, 0.95, 0.95)),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(t)
        story.append(Spacer(1, 12))
        
        story.append(Paragraph("Simple Summary:", styles['Heading4']))
        story.append(Paragraph(simple_explanation, styles['Normal']))
        story.append(Spacer(1, 12))
        
    # Disclaimer
    story.append(Spacer(1, 24))
    story.append(Paragraph("DISCLAIMER: This report is generated by an AI model. All strategic decisions should be reviewed by human experts.", styles['Italic']))

    doc.build(story)
    print(f"Report generated at {filepath}")

if __name__ == "__main__":
    # Test
    dummy_res = [{
        'segment': 'SMB',
        'new_price': 120,
        'revenue_uplift_pct': 15.5,
        'churn_probability': 0.12,
        'risk_label': 'Low Risk',
        'risk_score': 10
    }]
    generate_pdf_report(dummy_res, "test_report.pdf")
